version: "3.7"
services: 

  mssql:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: mysqlDB
        target: /var/lib/mysql
    networks:
      app_net:

volumes:
  mysqlDB:
networks: 
  app_net:
