version: "3.9"
services: 

  mssql:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - type: volume
          source: mysqlDB
          target: /var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${MYSQL_IP}

volumes:
  mysqlDB:
networks: 
  app_net:
