version: "3.7"
services: 

  mssql:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: mysqlDB
        target: /var/lib/mysql
    networks:
      app_net:
  
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
      args:
        app42.paas.db.ip: mssql
        app42.paas.db.port: "${MYSQL_PORT}"
        app42.paas.db.username: "${MYSQL_USER}"
        app42.paas.db.password: "${MYSQL_PASSWORD}"
        app42.paas.db.name: "${MYSQL_DATABASE}"
    image: viklosh/simpapp
    volumes: 
      - type: volume
        source: app
        target: /usr/local/tomcat/webapps
    networks:
      app_net:


volumes:
  mysqlDB:
  app:
networks: 
  app_net:
