version: "3.9"
services: 

  mssql:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:
        ipv4_address: ${APP_IP}
networks: 
  app_net:
